version: "3.5"
services:
  web:
    build: .
    container_name: chowly-demo
    command: npm run dev
    image: node:alpine3.18
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules/
    networks:
      - demo-network
networks:
  demo-network:
    name: demo-network
