version: "3.5"
services:
  web:
    build: .
    container_name: chowly-backend-demo
    image: python:3.8
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/app
    environment:
      - FLASK_ENV=development
    networks:
      - demo-network
networks:
  demo-network:
    name: demo-network
